# https://taskfile.dev

version: '3'

vars:
  REPOSITORY: index.docker.io/platformplane/platform-catalog-azure:v0.2.3

tasks:
  publish:
    dir: package
    cmds:
      - crossplane xpkg build -o platform-catalog-azure.xpkg
      - crossplane xpkg push -f platform-catalog-azure.xpkg {{.REPOSITORY}}
      - rm platform-catalog-azure.xpkg