apiVersion: catalog.cluster.local/v2
kind: AzureFunction
metadata:
  name: azurefunction-sample
spec:
  parameters:
    location: Switzerland North
    image: mcr.microsoft.com/azure-functions/node:4-node22
    environmentVariables:
      - key: EXAMPLE_SETTING
        value: example-value
