apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azurestorages.catalog.cluster.local
spec:
  compositeTypeRef:
    apiVersion: catalog.cluster.local/v1
    kind: AzureStorageComposite

  writeConnectionSecretsToNamespace: crossplane-system

  mode: Pipeline
  pipeline:
    - step: get-environment-configs
      functionRef:
        name: crossplane-contrib-function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Reference
              ref:
                name: azure-environment

    - step: storage-account
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |

            {{ $composite := $.observed.composite.resource }}
            {{ $claim := $composite.spec.claimRef }}
            {{ $account := $.observed.resources.account }}

            apiVersion: storage.azure.upbound.io/v1beta1
            kind: Account
            metadata:
              name: {{ $claim.name }}-account
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: account
            {{ if eq $claim nil }}
                crossplane.io/external-name: {}
            {{ else }}
                crossplane.io/external-name: {{ regexReplaceAll "[^a-z0-9]" (printf "%s" $composite.metadata.uid | lower) "" | trunc 24 }}
            {{ end }}
            spec:
              forProvider:
                resourceGroupName: {{ index $.context "apiextensions.crossplane.io/environment" "resourcegroup" }}
                location: {{ default "Switzerland North" $composite.spec.location }}               # called Region in Azure UI
                accountReplicationType: {{ default "LRS" $composite.spec.accountReplicationType }} # called Replication in Azure UI
                accountTier: {{ default "Standard" $composite.spec.accountTier }}                  # called Performance in Azure UI
                publicNetworkAccessEnabled: {{ default "false" $composite.spec.public }}
                allowNestedItemsToBePublic: false
                tags:
                  source: crossplane
                  claim-name: {{ $claim.name }}
                  claim-kind: {{ $claim.kind }}
                  claim-api-version: {{ $claim.apiVersion }}
                  composite: {{ $composite.metadata.uid }}
              writeConnectionSecretToRef:
                namespace: {{ $claim.namespace }}
                name: {{ $claim.name }}-connection

            ---
            apiVersion: network.azure.upbound.io/v1beta1
            kind: PrivateEndpoint
            metadata:
              name: {{ $claim.name }}-blob
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: endpointblob
                crossplane.io/external-name: {{ $claim.name }}-blob
            spec:
              forProvider:
                resourceGroupName: {{ index $.context "apiextensions.crossplane.io/environment" "resourcegroup" }}
                subnetId: "/subscriptions/{{ index $.context "apiextensions.crossplane.io/environment" "network-subscription" }}/resourceGroups/{{ index $.context "apiextensions.crossplane.io/environment" "network-resourcegroup" }}/providers/Microsoft.Network/virtualNetworks/{{ index $.context "apiextensions.crossplane.io/environment" "network-name" }}/subnets/default"
                location: {{ index $.context "apiextensions.crossplane.io/environment" "network-location" }} # needs to be the same region as the network
                customNetworkInterfaceName: {{ $claim.name }}-blob-nic
                privateServiceConnection:
                  - isManualConnection: false
                    name: {{ $claim.name }}-blob
                    privateConnectionResourceId: {{ $account.resource.status.atProvider.id }}
                    subresourceNames:
                      - blob
                privateDnsZoneGroup:
                  - name: default
                    privateDnsZoneIds:
                      - "/subscriptions/{{ index $.context "apiextensions.crossplane.io/environment" "network-subscription" }}/resourceGroups/{{ index $.context "apiextensions.crossplane.io/environment" "network-resourcegroup" }}/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net"
                tags:
                  source: crossplane
                  claim-name: {{ $claim.name }}
                  claim-kind: {{ $claim.kind }}
                  claim-api-version: {{ $claim.apiVersion }}
                  composite: {{ $composite.metadata.uid }}

            ---
            apiVersion: network.azure.upbound.io/v1beta1
            kind: PrivateEndpoint
            metadata:
              name: {{ $claim.name }}-file
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: endpointfile
                crossplane.io/external-name: {{ $claim.name }}-file
            spec:
              forProvider:
                resourceGroupName: {{ index $.context "apiextensions.crossplane.io/environment" "resourcegroup" }}
                subnetId: "/subscriptions/{{ index $.context "apiextensions.crossplane.io/environment" "network-subscription" }}/resourceGroups/{{ index $.context "apiextensions.crossplane.io/environment" "network-resourcegroup" }}/providers/Microsoft.Network/virtualNetworks/{{ index $.context "apiextensions.crossplane.io/environment" "network-name" }}/subnets/default"
                location: {{ index $.context "apiextensions.crossplane.io/environment" "network-location" }} # needs to be the same region as the network
                customNetworkInterfaceName: {{ $claim.name }}-file-nic
                privateServiceConnection:
                  - isManualConnection: false
                    name: {{ $claim.name }}-file
                    privateConnectionResourceId: {{ $account.resource.status.atProvider.id }}
                    subresourceNames:
                      - file
                privateDnsZoneGroup:
                  - name: default
                    privateDnsZoneIds:
                      - "/subscriptions/{{ index $.context "apiextensions.crossplane.io/environment" "network-subscription" }}/resourceGroups/{{ index $.context "apiextensions.crossplane.io/environment" "network-resourcegroup" }}/providers/Microsoft.Network/privateDnsZones/privatelink.file.core.windows.net"
                tags:
                  source: crossplane
                  claim-name: {{ $claim.name }}
                  claim-kind: {{ $claim.kind }}
                  claim-api-version: {{ $claim.apiVersion }}
                  composite: {{ $composite.metadata.uid }}

            ---
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            metadata:
            {{ if eq $.observed.resources nil }}
            data: {}
            {{ else }}
            data:
              {{- $accountName := index $account.resource.metadata.annotations "crossplane.io/external-name" }}
              blob-host: {{ printf "%s.blob.core.windows.net" $accountName | b64enc }}
              file-host: {{ printf "%s.file.core.windows.net" $accountName | b64enc }}
              username: {{ $accountName | b64enc }}
              public: {{ printf "%t" $account.resource.status.atProvider.publicNetworkAccessEnabled | b64enc }}
              {{ if ne $account.connectionDetails nil }}
              password: {{ index $account.connectionDetails "attribute.primary_access_key" }}
              uri: {{ trimPrefix "DefaultEndpointsProtocol=https;BlobEndpoint=" (index $account.connectionDetails "attribute.primary_blob_connection_string" | b64dec) | b64enc }}
              {{ end }}
            {{ end }}

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready

    - step: enforce-creation-sequence
      functionRef:
        name: crossplane-contrib-function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
            - "account"
            - "endpointblob"
          - sequence:
            - "account"
            - "endpointfile"
